require:
  - standard

plugins:
  - standard-custom
  - standard-performance
  - rubocop-performance

inherit_gem:
  standard: config/ruby-3.3.yml
  standard-custom: config/base.yml
  standard-performance: config/base.yml

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.4

Lint/UselessConstantScoping:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true
  SafeAutoCorrect: true
