require:
  - standard

inherit_gem:
  standard: config/ruby-3.3.yml

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.4

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true
  SafeAutoCorrect: true
