# frozen_string_literal: true

require "tmpdir"

RSpec.describe Site::Sponsors::Refresh do
  subject(:refresh) {
    described_class.new(github: source(github), open_collective: source(open_collective), config:, output_path:)
  }

  let(:config) {
    Site::Sponsors::Config.new(github_login: "hanami", open_collective_slug: "hanami", one_time_donation_months: 12)
  }
  let(:output_path) { Pathname(Dir.mktmpdir).join("sponsors.yml") }
  let(:open_collective) { Site::Sponsors::Listing.new(sponsors: [], private_count: 0) }

  def source(listing)
    instance_double(Site::Sponsors::GitHub, call: listing)
  end

  def listing(named, private_count: 0)
    Site::Sponsors::Listing.new(sponsors: named.map { |handle| sponsor(handle) }, private_count:)
  end

  def sponsor(handle)
    {
      "source" => "github", "name" => handle, "handle" => handle,
      "profile_url" => "https://github.com/#{handle}", "avatar_url" => "https://example.com/#{handle}.png"
    }
  end

  def write_existing(named_count, private_count: 0)
    contents = {
      "private_count" => private_count,
      "sponsors" => Array.new(named_count) { |i| sponsor("existing-#{i}") }
    }
    output_path.write(contents.to_yaml)
  end

  describe "writing the file" do
    let(:github) { listing(["ada", "zoe"], private_count: 3) }

    it "writes the named sponsors and a count of the private ones" do
      refresh.call

      written = YAML.load_file(output_path)
      expect(written.fetch("sponsors").map { it["handle"] }).to eq ["ada", "zoe"]
      expect(written.fetch("private_count")).to eq 3
    end

    it "marks the file as generated" do
      refresh.call

      expect(output_path.read).to include "# Generated by `bundle exec rake sponsors:refresh`"
    end

    it "indents the sponsors list, matching our other YAML files" do
      refresh.call

      expect(output_path.read).to include "sponsors:\n  - source: github\n    name: ada\n"
    end

    context "when a name needs quoting" do
      let(:github) {
        Site::Sponsors::Listing.new(sponsors: [sponsor("ada").merge("name" => %(Ada: "The Countess" #1))], private_count: 0)
      }

      it "writes it so it reads back unchanged" do
        refresh.call

        expect(YAML.load_file(output_path).fetch("sponsors").first.fetch("name")).to eq %(Ada: "The Countess" #1)
      end
    end
  end

  describe "guarding against a bad refresh" do
    context "when the sources return nothing" do
      let(:github) { listing([]) }

      it "raises rather than emptying the list" do
        write_existing(10)

        expect { refresh.call }.to raise_error RuntimeError, /empty sponsors list/
        expect(YAML.load_file(output_path).fetch("sponsors").length).to eq 10
      end
    end

    context "when the list would shrink sharply" do
      let(:github) { listing(Array.new(5) { |i| "kept-#{i}" }) }

      it "raises and leaves the file alone" do
        write_existing(20)

        expect { refresh.call }.to raise_error RuntimeError, /down from 20/
        expect(YAML.load_file(output_path).fetch("sponsors").length).to eq 20
      end
    end

    context "when a few sponsors have moved on" do
      let(:github) { listing(Array.new(9) { |i| "kept-#{i}" }) }

      it "writes the smaller list" do
        write_existing(10)
        refresh.call

        expect(YAML.load_file(output_path).fetch("sponsors").length).to eq 9
      end
    end

    context "when private sponsors make up the difference" do
      let(:github) { listing(Array.new(9) { |i| "kept-#{i}" }, private_count: 9) }

      it "counts them towards the total" do
        write_existing(18)
        refresh.call

        expect(YAML.load_file(output_path).fetch("private_count")).to eq 9
      end
    end
  end
end
