# frozen_string_literal: true

require "yaml"

module Site
  module Sponsors
    # Rebuilds content/sponsors/sponsors.yml from the given sponsor sources.
    #
    # Writing to this file runs past a number of guards: a run that returns no sponsors, or far
    # fewer than last time, aborts without touching the file. An expired token or a partial API
    # response must never remove legitimate sponsors.
    class Refresh
      OUTPUT_PATH = App.root.join("content/sponsors/sponsors.yml")

      # A refresh may not drop more than this share of the sponsors we already list.
      MINIMUM_RETAINED_FRACTION = 0.8

      HEADER = <<~YAML
        # The people who sponsor Hanakai as individuals. Shown on the sponsor page.
        #
        # Generated by `bundle exec rake sponsors:refresh`. Do not edit by hand. To add, remove or
        # merge someone, edit content/sponsors/config.yml and run the task again.
      YAML

      def initialize(github:, open_collective:, config:, output_path: OUTPUT_PATH)
        @github = github
        @open_collective = open_collective
        @config = config
        @output_path = output_path
      end

      def call
        result = Compiler.new(@config).call(
          github: @github.call,
          open_collective: @open_collective.call
        )

        check result
        write result

        result
      end

      private

      def check(result)
        total = total_of(result)

        raise "Refusing to write an empty sponsors list" if total.zero?

        floor = (previous_total * MINIMUM_RETAINED_FRACTION).floor
        return if total >= floor

        raise <<~MSG.chomp
          Refusing to write #{total} sponsors, down from #{previous_total}.
          This usually means an API call failed or a token expired. Check the APIs, then re-run.
        MSG
      end

      def total_of(result)
        result.sponsors.length + result.private_count
      end

      def previous_total
        @previous_total ||=
          if @output_path.exist?
            previous = YAML.load_file(@output_path)

            unless previous.is_a?(Hash) && previous.key?("sponsors") && previous.key?("private_count")
              raise "#{@output_path} is not a sponsors file. Delete it and run this task again."
            end

            previous.fetch("sponsors").length + previous.fetch("private_count")
          else
            0
          end
      end

      def write(result)
        @output_path.write(HEADER + {"private_count" => result.private_count}.to_yaml + sponsors_yaml(result.sponsors))
      end

      # Psych writes a list flush with its parent key. We indent it by two spaces to match the rest
      # of our YAML files. Psych still does the quoting, so names with colons or quotes stay valid.
      def sponsors_yaml(sponsors)
        return "sponsors: []\n" if sponsors.empty?

        list = sponsors.to_yaml.delete_prefix("---\n")
        "sponsors:\n" + list.gsub(/^(?=.)/, "  ")
      end
    end
  end
end
