# auto_register: false
# frozen_string_literal: true

module Site
  module Content
    module Filters
      # Sanitizes heading anchor IDs for URI compatibility.
      #
      # Processes heading anchors auto-generated by the markdown processor and ensures their `href`
      # and `id` attributes contain only ASCII characters.
      #
      # This is necessary for the URI parsing done during our static build, which requires
      # ASCII-only URIs, as part of RFC3986 compliance.
      #
      # With this filter in place, a heading like "# How to install ⌨️" will have its anchor ID
      # sanitized from "#how-to-install-⌨️" to "#how-to-install".
      #
      # This filter should run before {LinkableHeadingsFilter} in our HTML pipelines.
      class SanitizeHeadingAnchorsFilter < HTMLPipeline::NodeFilter
        SELECTOR = Selma::Selector.new(
          match_element: "h1 a[href], h2 a[href], h3 a[href], h4 a[href], h5 a[href], h6 a[href]"
        )

        def selector = SELECTOR

        def handle_element(element)
          heading_href = element["href"]

          return unless heading_href&.start_with?("#")

          heading_id = heading_href[1..]
          sanitized_id = sanitize(heading_id)

          return if sanitized_id == heading_id

          element["href"] = "##{sanitized_id}"
          element["id"] = sanitized_id if element["id"]
        end

        private

        def sanitize(value)
          value
            .gsub(/[^\x00-\x7F]/, "") # Remove non-ASCII characters
            .gsub(/^[-_]+|[-_]+$/, "") # Remove leading and trailing hyphens/underscores
        end
      end
    end
  end
end
